In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("student_marks.csv")
df

      Name    Stream  Percentage
0     Ajay      Math          88
1     Amit  Commerce          92
2  Keerthi   Science          95
3     Prem      Math          70
4    Priya      Math          65
5   Pragna   Science          78

In [6]:
df[df['Percentage'] > 80]

      Name    Stream  Percentage
0     Ajay      Math          88
1     Amit  Commerce          92
2  Keerthi   Science          95

In [7]:
df.loc[df['Percentage'] > 80]

      Name    Stream  Percentage
0     Ajay      Math          88
1     Amit  Commerce          92
2  Keerthi   Science          95

In [8]:
df.loc[:, ['Name', 'Percentage']]

      Name  Percentage
0     Ajay          88
1     Amit          92
2  Keerthi          95
3     Prem          70
4    Priya          65
5   Pragna          78

In [9]:
df.loc[df['Percentage'] > 80, ['Name', 'Percentage']]

      Name  Percentage
0     Ajay          88
1     Amit          92
2  Keerthi          95

In [11]:
df.loc[df['Name'] == 'Ajay', 'Percentage'] = 90
df

      Name    Stream  Percentage
0     Ajay      Math          90
1     Amit  Commerce          92
2  Keerthi   Science          95
3     Prem      Math          70
4    Priya      Math          65
5   Pragna   Science          78

In [12]:
df[(df['Percentage'] > 90) & (df['Stream'] == 'Science')]

      Name   Stream  Percentage
2  Keerthi  Science          95

In [13]:
df[df['Stream'] != 'Math']

      Name    Stream  Percentage
1     Amit  Commerce          92
2  Keerthi   Science          95
5   Pragna   Science          78

In [14]:
df.iloc[:2, :2]

   Name    Stream
0  Ajay      Math
1  Amit  Commerce

In [15]:
df.sort_values(by='Stream')

      Name    Stream  Percentage
1     Amit  Commerce          92
0     Ajay      Math          90
3     Prem      Math          70
4    Priya      Math          65
2  Keerthi   Science          95
5   Pragna   Science          78

In [16]:
df.drop(df[df['stream'] == 'Math'].index, inplace=True)

      Name    Stream  Percentage
1     Amit  Commerce          92
2  Keerthi   Science          95
5   Pragna   Science          78